name: bhasha_dristi
description: A transliteration and OCR app built with Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  camera: ^0.10.5+9
  image_picker: ^1.1.2
  image_cropper: ^7.0.0

  http: ^1.2.1
  http_parser: ^4.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.0

  share_plus: ^10.0.0
  clipboard: ^0.1.3
  intl: ^0.19.0

  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#1C2331"
  adaptive_icon_foreground: "assets/icon.png"